name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/status/**'
      - 'vite.config.ts'
      - 'package.json'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -D terser
        
      - name: Build main app
        run: npm run build
        env:
          BASE_URL: /interactive-node-network/
          NODE_ENV: production
        
      - name: Build status dashboard
        run: |
          # Generate health report
          npm run docs:health || true
          
          # Copy status dashboard files
          mkdir -p dist/status
          cp -r docs/status/* dist/status/ || true
          
          # Ensure index.html exists in root
          if [ ! -f dist/index.html ]; then
            cp dist/status/index.html dist/index.html || true
          fi
        env:
          NODE_OPTIONS: --experimental-specifier-resolution=node
        
      - name: List files
        run: |
          echo "Contents of dist directory:"
          ls -la dist/
          echo "\nContents of dist/status directory:"
          ls -la dist/status/ || echo "status directory not found"
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true 