name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'docs/status/**'
      - 'vite.config.ts'
      - 'package.json'
      - '.github/workflows/deploy.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install -D terser
        
      - name: Build
        run: |
          # Build the main app
          npm run build
          
          # Generate and copy status dashboard
          npm run docs:health || true
          mkdir -p dist/status
          cp -r docs/status/* dist/status/ || true
        env:
          BASE_URL: /interactive-node-network/
          NODE_OPTIONS: --experimental-specifier-resolution=node
        
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
          force_orphan: true 