name: Documentation Check

on:
  push:
    paths:
      - '**/*.md'
      - 'scripts/docs/**'
  pull_request:
    paths:
      - '**/*.md'
      - 'scripts/docs/**'

jobs:
  check-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Check documentation links
        run: npm run docs:check-links
        
      - name: Check documentation coverage
        run: npm run docs:coverage 