name: Documentation Checks

on:
  # Only run on changes to documentation files
  push:
    branches: [ main ]
    paths:
      - 'docs/[!s]*/**'    # All docs folders except those starting with 's'
      - 'docs/[a-r]*/**'   # Docs folders a through r
      - 'docs/[t-z]*/**'   # Docs folders t through z
      - '**.md'
  pull_request:
    branches: [ main ]
    paths:
      - 'docs/[!s]*/**'    # All docs folders except those starting with 's'
      - 'docs/[a-r]*/**'   # Docs folders a through r
      - 'docs/[t-z]*/**'   # Docs folders t through z
      - '**.md'

jobs:
  check-documentation:
    runs-on: ubuntu-latest
    # Skip if it's a dashboard deployment
    if: "!contains(github.event.head_commit.message, 'deploy-dashboard')"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run documentation checks
        run: |
          echo "Running documentation checks (non-blocking)"
          npm run docs:check || echo "Docs check completed"
          npm run docs:coverage || echo "Coverage check completed"

      - name: Update checksums
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          echo "Updating checksums (non-blocking)"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          npm run docs:update-checksums || echo "No checksums to update"
          git add .checksums.json || echo "No checksums to add"
          git commit -m "chore: update documentation checksums" || echo "No changes to commit"
          git push || echo "No changes to push" 